services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Etc/UTC
    volumes:
      - ${HOME}/services/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped