services:
  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - 8080:80
    user: "${UID}:${GID}"
    restart: unless-stopped
    volumes:
      - /home/riccardo/DataVol/:/srv
      - /home/riccardo/services/filebrowser/database:/database
      - /home/riccardo/services/filebrowser/config:/config
