services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ${HOME}/services/homer/config:/www/assets
    ports:
      - 3000:8080
    user: ${UID}:${GID}
    environment:
      - INIT_ASSETS=1
    restart: unless-stopped
